//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PayMent
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Xin hãy nhập giá tiền!")]

        public Nullable<double> Cash { get; set; }
        public int UserId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        [Required(ErrorMessage = "Xin hãy nhập ảnh hóa đơn!")]
        [StringLength(100, ErrorMessage = "Địa tối đa chỉ được {1} kí tự!")]
        public string ImageUrl { get; set; }
        public Nullable<bool> Invisible { get; set; }
        public Nullable<System.DateTime> DatePay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
