//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Store
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Hãy nhập tên nguyên liệu!")]
        [StringLength(50, ErrorMessage = "Tên nguyên liệu tối đa chỉ được {1} kí tự!")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Hãy nhập giá nguyên liệu!")]
        public Nullable<double> ProductPrice { get; set; }
        [Required(ErrorMessage = "Hãy nhập tên nhà cung cấp!")]
        [StringLength(50, ErrorMessage = "Nhà cung cấp tối đa chỉ được {1} kí tự!")]
        public string SupplierName { get; set; }
        [Required(ErrorMessage = "Hãy nhập đơn vị của nguyên liệu!")]
        [StringLength(50, ErrorMessage = "Đơn vị tối đa chỉ được {1} kí tự!")]
        public string Note { get; set; }
        [Required(ErrorMessage = "Hãy nhập thời gian nhập kho!")]
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> InputQ { get; set; }
        public Nullable<int> OutputQ { get; set; }
        [Required(ErrorMessage = "Hãy nhập số lượng nguyên liệu!")]
        public Nullable<int> CurrentQ { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<bool> Invisible { get; set; }
        public string Category { get; set; }

        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Square { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
