//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCompany.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.PayMents = new HashSet<PayMent>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Xin hãy nhập tên!")]
        [RegularExpression(@"^[a-zA-Z ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệếỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ]+$", ErrorMessage = "Tên không được chứa kí tự đặc biệt!!!")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Tên cò độ dài nằm trong khoảng từ 5 đến 50 kí tự!")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Hãy nhập địa chỉ email!")]
        [StringLength(50, ErrorMessage = "Email tối đa chỉ được {1} kí tự!")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }
        [Required(ErrorMessage = "Hãy nhập địa chỉ!")]
        [StringLength(100, ErrorMessage = "Địa tối đa chỉ được {1} kí tự!")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Hãy nhập số điện thoại!")]
        [StringLength(15, ErrorMessage = "Số điện thoại phải là dãy số tối thiểu có 9 số và tối đa là 15 số!")]
        [RegularExpression(@"[0-9]*\.?[0-9]+", ErrorMessage = "Số điện thoại phải là dãy số tối thiểu có 9 số và tối đa là 15 số!")]
        [MinLength(9, ErrorMessage = "Số điện thoại phải là dãy số tối thiểu có 9 số và tối đa là 15 số!")]
        public string PhoneNumber { get; set; }
        public Nullable<int> CreatorId { get; set; }
        [Required(ErrorMessage = "Hãy nhập tên công ty!")]
        [StringLength(100, ErrorMessage = "Địa tối đa chỉ được {1} kí tự!")]
        public string CompanyName { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateCreater { get; set; }
           [StringLength(100, ErrorMessage = "Địa chỉ đường dẫn của ảnh tối đa chỉ được {1} kí tự!")]
        public string ImageURL { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Invisible { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<PayMent> PayMents { get; set; }
    }
}
